# Generated by Django 2.0.13 on 2019-06-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('A', 'Adicionado'), ('C', 'Concluído')], default='A', max_length=2),
        ),
    ]
