# Generated by Django 2.0.13 on 2019-06-05 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='birth_day',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
